= Pax Warp 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: Pax Warp 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== Purpose

Pax Warp is a tool for managing relational database schemas and data sets in a system-independent
format.

Pax Warp is implemented in Java 8. You can use it as a stand-alone tool via its command line
interface, or embed it into Java EE 7 or OSGi applications, using the dependency injection framework
of the given platform (i.e. CDI or Declarative Services).

== Managing stuctural changes

The central concept of Pax Warp is a *change log*, representing a sequence of *change sets*, each
containing a number of *actions* applied to a given database.

Starting from an empty database, you can set up the initial schema by elementary actions such as
`createTable, addForeignKey, createIndex` etc.

As the schema evolves, you create additional change sets with actions like `addColumn, dropTable`
etc. to transform the database schema into the desired state.

Thus, a change log captures the version history of a given database schema. When applying a change
log to a database, Pax Warp tracks all applied change sets in a history table, skipping any
change set that has been applied in a previous run.

Applying a change log to a database is an *idempotent* operation. When adding one or more change
sets to a change log and applying the change log again, only the new change sets will be applied
to the database.  

== Managing data sets

Besides representing structural changes, a change log can also represent a data set as a sequence
of `insert` actions in a system independent way. Using Pax Warp, you can export data from a given
database and import them into another database, even on a different database management system.

This is mainly intended to manage small data sets as fixtures for integration or system
tests of applications supporting multiple database management systems. Pax Warp should *not* be 
used as a database backup tool.

== Supported database systems

Pax Warp currently supports the following relational database management systems:

* Apache Derby
* H2
* MySQL
* PostgreSQL

Any relational database with a JDBC driver can be supported by Pax Warp by adding a set of
SQL templates and a new DBMS profile.

= Getting Started

bla bla bla foo

// Return to normal title levels 
:leveloffset: 0
